### ISSUE TITLE
StringUtil class missing exception

### ISSUE THREAD

**Issue by sanjiv1980** [b23llc/nifi-fn-operator#3]
I got this below error while testing simple job, I have deployed on EKS (AWS).
```
SLF4J: Found binding in [jar:file:/usr/share/nifi-1.8.0/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/share/nififn/lib/slf4j-log4j12-1.6.1.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
06:23:35.331 [main] INFO org.apache.nifi.processors.standard.GenerateFlowFile - GenerateFlowFile[id=7b0413c7-6a8b-4db7-b991-5af9f281ef10] GenerateFlowFile validated
06:23:35.334 [main] INFO org.apache.nifi.processors.standard.LogAttribute - LogAttribute[id=897b9f54-28bb-4c2f-8fba-7d1ccb0a44df] LogAttribute validated
06:23:35.334 [main] INFO org.apache.nifi.processors.standard.GenerateFlowFile - GenerateFlowFile[id=7b0413c7-6a8b-4db7-b991-5af9f281ef10] Running GenerateFlowFile.onTrigger with 0 records
06:23:35.348 [main] INFO org.apache.nifi.processors.standard.LogAttribute - LogAttribute[id=897b9f54-28bb-4c2f-8fba-7d1ccb0a44df] Running LogAttribute.onTrigger with 6 records
Exception in thread "main" java.lang.NoClassDefFoundError: org/eclipse/jetty/util/StringUtil
	at org.apache.nifi.processors.standard.LogAttribute.processFlowFile(LogAttribute.java:179)
	at org.apache.nifi.processors.standard.LogAttribute.onTrigger(LogAttribute.java:316)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:27)
	at org.apache.nifi.fn.core.FnProcessorWrapper.runRecursive(FnProcessorWrapper.java:147)
	at org.apache.nifi.fn.core.FnProcessorWrapper.runChildren(FnProcessorWrapper.java:205)
	at org.apache.nifi.fn.core.FnProcessorWrapper.lambda$null$3(FnProcessorWrapper.java:157)
	at org.apache.nifi.fn.core.FnProcessSession.commit(FnProcessSession.java:610)
	at org.apache.nifi.processor.AbstractProcessor.onTrigger(AbstractProcessor.java:28)
	at org.apache.nifi.fn.core.FnProcessorWrapper.runRecursive(FnProcessorWrapper.java:147)
	at org.apache.nifi.fn.core.FnFlow.runOnce(FnFlow.java:201)
	at org.apache.nifi.fn.runtimes.Program.main(Program.java:104)
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.util.StringUtil
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more```

**Comment by dbkegley** [comment]
I have seen that before as well when using the LogAttribute and LogMessage processors. That error is related to the nifi-stateless image. Unfortunately that's not something I can fix here. 

I just tested this with the 1.10-0-SNAPSHOT build and it appears to be fixed in master

```
12:55:12.760 [main] INFO org.apache.nifi.processors.standard.LogAttribute - LogAttribute[id=57b70bb5-7abd-3abb-806f-fab7eed14bd4] logging for flow file {"attributes":{"absolute.path":"/tmp/nifistateless/input/","path":"target","filename":"test2.txt","uuid":"6bd13eb8-7168-4e7b-bce9-12107fbeb3df"}}
--------------------------------------------------
Standard FlowFile Attributes
Key: 'entryDate'
	Value: 'Thu Aug 22 12:55:12 GMT 2019'
Key: 'lineageStartDate'
	Value: 'Thu Aug 22 12:55:12 GMT 2019'
Key: 'fileSize'
	Value: '2'
FlowFile Attribute Map Content
Key: 'absolute.path'
	Value: '/tmp/nifistateless/input/'
Key: 'filename'
	Value: 'test2.txt'
Key: 'path'
	Value: 'target'
Key: 'uuid'
	Value: '6bd13eb8-7168-4e7b-bce9-12107fbeb3df'
--------------------------------------------------
Flow Succeeded
```
